### PR TITLE
Adding support for CF-Connecting-IP and True-Client-IP

### PR DESCRIPTION
**Pull request by fluxsauce**
As mentioned in #20.

### CODE REVIEW

**Comment by pbojinov** [comment]
that was quick :)

**Comment by fluxsauce** [comment]
> that was quick :)

That's how I roll :-) I wanted to replace a fairly similar in-house system that did basically the same thing and this was the one difference, figured I'd add it here (contribute to the community) and reduce the number of reinvented wheels. LMK if there's anything I can do to adjust!

**Comment by pbojinov** [comment]
This is good, thank you. 

I'll get This merged over by tomorrow morning and let you know.

**Comment by pbojinov** [comment]
@fluxsauce good to go! Thanks again.

**Comment by fluxsauce** [comment]
Sweet, thanks!

**Pull request merged**
